#############################################################################
# Makefile for building: application
# Generated by qmake (3.0) (Qt 5.3.0)
# Project:  application.pro
# Template: app
# Command: /Users/NongFei/Qt5.3.0/5.3/clang_64/bin/qmake -o Makefile application.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../../../Qt5.3.0/5.3/clang_64/mkspecs/macx-clang -I. -I../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I../../../../Qt5.3.0/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../../../Qt5.3.0/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/AGL.framework/Headers -F/Users/NongFei/Qt5.3.0/5.3/clang_64/lib
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS) -F/Users/NongFei/Qt5.3.0/5.3/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Users/NongFei/Qt5.3.0/5.3/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp qrc_application.cpp \
		moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		qrc_application.o \
		moc_mainwindow.o
DIST          = ../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/qdevice.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/common/shell-unix.conf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/common/unix.conf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/common/mac.conf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/common/macx.conf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/common/clang.conf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/qconfig.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/precompile_header.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/qt.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/resources.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/moc.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/uic.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/lex.prf \
		application.pro main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = application
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = application

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk \
		-mmacosx-version-min=10.6 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: application.pro ../../../../Qt5.3.0/5.3/clang_64/mkspecs/macx-clang/qmake.conf ../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/qdevice.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/common/shell-unix.conf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/common/unix.conf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/common/mac.conf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/common/macx.conf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/common/clang.conf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/qconfig.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/precompile_header.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/qt.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/resources.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/moc.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/uic.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/lex.prf \
		application.pro \
		application.qrc \
		/Users/NongFei/Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/NongFei/Qt5.3.0/5.3/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/NongFei/Qt5.3.0/5.3/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile application.pro
../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/spec_pre.prf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/qdevice.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/device_config.prf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/common/shell-unix.conf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/common/unix.conf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/common/mac.conf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/common/macx.conf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/common/gcc-base.conf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/common/clang.conf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/common/clang-mac.conf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/qconfig.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/qt_functions.prf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/qt_config.prf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/macx-clang/qmake.conf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/default_pre.prf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/mac/default_pre.prf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/resolve_config.prf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/default_post.prf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/mac/sdk.prf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/mac/default_post.prf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/precompile_header.prf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/warn_on.prf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/qt.prf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/resources.prf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/moc.prf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/unix/opengl.prf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/uic.prf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/unix/thread.prf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/mac/rez.prf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/testcase_targets.prf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/exceptions.prf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/yacc.prf:
../../../../Qt5.3.0/5.3/clang_64/mkspecs/features/lex.prf:
application.pro:
application.qrc:
/Users/NongFei/Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/NongFei/Qt5.3.0/5.3/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/NongFei/Qt5.3.0/5.3/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile application.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/application1.0.0 || mkdir -p .tmp/application1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/application1.0.0/ && $(COPY_FILE) --parents application.qrc .tmp/application1.0.0/ && $(COPY_FILE) --parents mainwindow.h .tmp/application1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp .tmp/application1.0.0/ && (cd `dirname .tmp/application1.0.0` && $(TAR) application1.0.0.tar application1.0.0 && $(COMPRESS) application1.0.0.tar) && $(MOVE) `dirname .tmp/application1.0.0`/application1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/application1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_no_pch_compiler_make_all:
compiler_no_pch_compiler_clean:
compiler_rcc_make_all: qrc_application.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_application.cpp
qrc_application.cpp: application.qrc \
		images/copy.png \
		images/new.png \
		images/save.png \
		images/open.png \
		images/paste.png \
		images/cut.png
	/Users/NongFei/Qt5.3.0/5.3/clang_64/bin/rcc -name application application.qrc -o qrc_application.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: ../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		mainwindow.h
	/Users/NongFei/Qt5.3.0/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/NongFei/Qt5.3.0/5.3/clang_64/mkspecs/macx-clang -I/Users/NongFei/Documents/Workspace/qt_workspace/sqlformater -I/Users/NongFei/Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/NongFei/Qt5.3.0/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/NongFei/Qt5.3.0/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/NongFei/Qt5.3.0/5.3/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		mainwindow.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp ../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QtWidgets \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaccessiblewidget.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolordialog.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qerrormessage.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfilesystemmodel.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfontdialog.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qinputdialog.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qprogressdialog.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwizard.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicseffect.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsanchorlayout.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsgridlayout.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsitem.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsitemanimation.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslayout.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslayoutitem.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslinearlayout.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsproxywidget.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsscene.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicssceneevent.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicstransform.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsview.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicswidget.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractitemdelegate.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractitemview.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolumnview.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdatawidgetmapper.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdirmodel.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfileiconprovider.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qheaderview.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qitemdelegate.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qitemeditorfactory.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistview.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistwidget.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleditemdelegate.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtableview.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreeview.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidgetitemiterator.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaction.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qactiongroup.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdesktopwidget.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qformlayout.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgesture.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgesturerecognizer.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgridlayout.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlayout.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlayoutitem.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qshortcut.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsizepolicy.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstackedlayout.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtooltip.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwhatsthis.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidgetaction.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qkeyeventtransition.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmouseeventtransition.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcommonstyle.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdrawutil.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qproxystyle.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyle.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstylefactory.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleoption.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstylepainter.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleplugin.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolormap.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcompleter.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscroller.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscrollerproperties.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsystemtrayicon.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qundogroup.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qundostack.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qundoview.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractbutton.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractscrollarea.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractslider.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractspinbox.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qbuttongroup.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcalendarwidget.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcheckbox.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcombobox.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcommandlinkbutton.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdatetimeedit.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdial.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialogbuttonbox.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdockwidget.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfocusframe.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfontcombobox.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qframe.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgroupbox.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qkeysequenceedit.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlcdnumber.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlineedit.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmdiarea.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmdisubwindow.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qplaintextedit.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qprogressbar.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qradiobutton.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qrubberband.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscrollarea.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscrollbar.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsizegrip.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qslider.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qspinbox.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsplashscreen.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsplitter.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstackedwidget.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstatusbar.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtabbar.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtabwidget.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextbrowser.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextedit.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbar.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbox.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbutton.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtwidgetsversion.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QRegExp \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qregexp.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtDebug \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		mainwindow.h \
		../../../../Qt5.3.0/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

qrc_application.o: qrc_application.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_application.o qrc_application.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

